### ISSUE TITLE
debounce, skip, and throttleFirst

### ISSUE THREAD

**Issue by Noddy20** [LDRAlighieri/Corbind#11]
What about debounce, skip, and throttleFirst functions of RxBinding to skip text input and multiple clicks?

**Comment by LDRAlighieri** [comment]
These functions are not part of RxBinding, they are part of RxJava ([debounce][rxdebounce], [skip][rxskip], [throttleFirst][rxthrottleFirst]).
For example, for Flow there are analogues of the functions you need: [debounce][flowdebounce], [drop][flowdrop]. I advise you to read the list of [extensions][flow].
There is no analogue for throttleFirst, but we can create it:

```kotlin
@FlowPreview
@ExperimentalCoroutinesApi
fun <T> Flow<T>.throttleFirst(windowDuration: Long): Flow<T> = flow {
    var lastEmissionTime = 0L
    collect { upstream ->
        val currentTime = (coroutineContext[ContinuationInterceptor] as? DelayController)?.currentTime
            ?: System.currentTimeMillis()
        if (currentTime - lastEmissionTime > windowDuration) {
            lastEmissionTime = currentTime
            emit(upstream)
        }
    }
}
```

[rxdebounce]: https://github.com/ReactiveX/RxJava/wiki/Filtering-Observables#debounce
[rxskip]: https://github.com/ReactiveX/RxJava/wiki/Filtering-Observables#skip
[rxthrottleFirst]: https://github.com/ReactiveX/RxJava/wiki/Filtering-Observables#throttlefirst
[flowdebounce]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/debounce.html
[flowdrop]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/drop.html
[flow]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/

**Comment by Noddy20** [comment]
Got it.
Thank you.
