### ISSUE TITLE
StateFlow Migration?

### ISSUE THREAD

**Issue by Volt316** [LDRAlighieri/Corbind#12]
Are there any plans to migrate over to StateFlow?

**Comment by LDRAlighieri** [comment]
Hello! I'll think about it.

**Comment by LDRAlighieri** [comment]
Much time and many disputes have passed. I still have doubts that there is a need for state flows for Android UI events. For the experiment, I added a transformer to the StateFlow for InitialValueFlow in version 1.5.0. Let's see how things go.
