### ISSUE TITLE
Sources jars are not published

### ISSUE THREAD

**Issue by ZacSweers** [LDRAlighieri/Corbind#6]
FYI, these appear to be missing from publishing and result in only being able to view decompiled class files when consuming

**Comment by LDRAlighieri** [comment]
Forgot to use `android.sourceSets.main.java.srcDirs` instead of `android.sourceSets.main.java.sourceFiles` to include Kotlin files. I will fix it. Thank you.

**Comment by LDRAlighieri** [comment]
Fixed in 1.1.0
